### ISSUE TITLE
call resume and pause functionality in function

### ISSUE THREAD

**Issue by rahuldev761** [volkov97/react-compound-timer#1]
Hi,
Thanks for creating such awesome control. I use it but facing a problem while calling start, resume, and pause functionality in a function. can you please tell me how I implement it.

**Comment by volkov97** [comment]
Hi!

I am happy, that you like it and using it in your project!

Here, in docs, you can see an example of how to use "start", "resume" and
"pause" functions.
https://www.npmjs.com/package/react-compound-timer#controls

Or maybe you can implement your case in https://codesandbox.io/ and then i
will try to help you there.

**Comment by volkov97** [comment]
Hope, that now everything is fine! Closing this issue!
