### ISSUE TITLE
How do I fire an event when time counts down to 0?

### ISSUE THREAD

**Issue by Chibuzo** [volkov97/react-compound-timer#15]
I need to fire an event when time counts down to zero. I thought onStop() hook would fire when the time elapses, but it only fires when time is stopped.

Please how can I know when time counts down to zero so I can fire an event?

Thanks

**Comment by volkov97** [comment]
you should use checkpoints with time: 0 and your callback

https://www.npmjs.com/package/react-compound-timer#with-checkpoints
