### ISSUE TITLE
TypeScript support !!!!!

### ISSUE THREAD

**Issue by CrazyAdmin** [volkov97/react-compound-timer#2]
Please add in package @types/index.d.ts
for support integration component with TypeScript in React

**Comment by volkov97** [comment]
Hi! I decided to rewrite all library in typescript. Do not worry, no api changes!

So, current version is 1.0.11, it is all in typescript, that's why you should have all typings in the box :)

Write me if you have any problems.

**Comment by Sun1ive** [comment]
faced an issue, fix path to your .d.ts files, because its not working
import { TimePartsType } from 'src/lib/helpers/getTimeParts';
import { TimerStateType } from 'src/lib/models/TimerState';

absolute path `src/...` doesn't work

**Comment by volkov97** [comment]
Hi, @Sun1ive!

Try to import them this way:

import { TimePartsType } from 'react-compound-timer/build/lib/helpers/getTimeParts';
import { TimerStateType } from 'react-compound-timer/build/lib/models/TimerState';

for me it is working

**Comment by Sun1ive** [comment]
can't test it right now, i believe its working

but if you will use autoimport via typescript, it will import like `src/...`;

**Comment by volkov97** [comment]
finally i figure out what was the problem)
sorry, just didn't have enougn time to look at this problem
hope that now everything is good
