### ISSUE TITLE
Gatsby build doesn't go through with ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by Natesan** [volkov97/react-compound-timer#20]
Tried to consume to module in a site built using Gatsby and when I try to run the gatsby build it fails with the following error.

> 9 |     function TimerModel(_a) {
10 |         var initialTime = _a.initialTime, direction = _a.direction, timeToUpdate = _a.timeToUpdate, lastUnit = _a.lastUnit, checkpoints = _a.checkpoints, onChange = _a.onChange;
 11 |         this.internalTime = performance.now();
    | ^
12 |         this.initialTime = initialTime;
13 |         this.time = initialTime;
14 |         this.direction = direction;

WebpackError: ReferenceError: performance is not defined

- TimerModel.js:11 new TimerModel
    node_modules/react-compound-timer/build/lib/models/TimerModel.js:11:1

- Timer.js:57 new Timer
    node_modules/react-compound-timer/build/components/Timer/Timer.js:57:1

**Comment by Dipeshwagle** [comment]
I think when it tries to build it the [Perfomance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) that is only available on browser causes build to fail. You can check the component in `typeof window !== 'undefined'` may solve that issue.

**Comment by lamarcharegresa** [comment]
Same error here, can you accept the pull request? Is working?

**Comment by zxpectre** [comment]
Same error here, can you accept the PR? It's working?

**Comment by YuhanJohn** [comment]
The PR is working, please accept it ! Thanks a lot ! :)

**Comment by williamadi92** [comment]
Please accept the PR. Because I'm facing the same problem in Next.js 🙂
