### ISSUE TITLE
Second  second is missing on backward countdown

### ISSUE THREAD

**Issue by irkinwork** [volkov97/react-compound-timer#24]
If you, for example, set initialTime={3000} you will see this sequence: 3, 1, 0.
But you expected to see: 3, 2, 1, 0.

Codesandbox example: https://codesandbox.io/s/boring-brook-b1mhx

I've found workaround. 
Default timeToUpdate is equal to 1000. But it's not enough to render every second. So we must use timeToUpdate < 1000.

**Comment by volkov97** [comment]
Right, if you set timeToUpdate less than 1000 - it should fix your problem :)
If you will have some problems again - reopen this issue, please!
