### ISSUE TITLE
performance is not defined on React Native

### ISSUE THREAD

**Issue by codigoconjuan** [volkov97/react-compound-timer#25]
I'm facing this problem on React Native

yesterday it was working well and today i was trying to check that everything works and this is broken

I think there's a PR already, tried to install again react-compound-timer but it didn't work

<img width="423" alt="Captura de Pantalla 2020-03-11 a la(s) 9 15 29" src="https://user-images.githubusercontent.com/5215691/76432686-ed7f7500-6378-11ea-980c-b160f6ea0a89.png">

**Comment by volkov97** [comment]
Hi! Should be fixed in 1.2.0
https://github.com/volkov97/react-compound-timer/pull/21
