### ISSUE TITLE
time not accurate

### ISSUE THREAD

**Issue by eltioxido** [volkov97/react-compound-timer#28]
Hi, how can I get an accurate time elapsed with this component? It seems if I lock my phone and get back to the browser, it slows down and after 5 minutes the timer has just counted 2-3 minutes :( I tried setting the timeToUpdate parameter to 100, pretty much the same result.

**Comment by volkov97** [comment]
Hi! Could you tell me what version are you using?

**Comment by eltioxido** [comment]
> Hi! Could you tell me what version are you using?

Thanks for replying! 

According to package-lock.json:
```
"react-compound-timer": {
      "version": "1.2.0",
```

**Comment by uadarsh** [comment]
It seems like we are relying to performance.now() [https://github.com/volkov97/react-compound-timer/blob/master/src/lib/helpers/now.ts] which does not work well with sleep time on most browsers.
https://medium.com/@mihai/performance-now-sleep-16a5b774560c
See a demo here - http://persistent.info/web-experiments/performance-now-sleep/

I suppose the idea of using performance.now must have been to not get influenced by user's time settings but this makes it virtually useless :(

**Comment by volkov97** [comment]
thank you for this info - updated now helper to use Date.now()
the idea about performance now was that it is more accurate.. since it is not - we removed it

so, please, you can try version 2.0.4
