### ISSUE TITLE
Need to have format value !

### ISSUE THREAD

**Issue by CrazyAdmin** [volkov97/react-compound-timer#3]
d:h:m:s = 0:0:0:0

also need to show 1h like 01, 1s like 01 and ....

**Comment by arieljaw12** [comment]
Hello

Is a way to get the second's value so we can do the formatting by hand?

Regards,
Ariel

**Comment by arieljaw12** [comment]
This is a workaround to format the seconds for example:

```
{(getTime() / 1000) % 60 < 10 ? '0' : null }<Timer.Seconds />
```

**Comment by volkov97** [comment]
@CrazyAdmin @arieljaw12 @kevinguebert
Now you can use formatValue property!

Look [here](https://volkov97.github.io/react-compound-timer/) for "Forward Count with formatting" example.

Avaliable in 1.0.12

**Comment by volkov97** [comment]
Closing this issue, hope everything is fine:)
