### ISSUE TITLE
Countdown timer jumps first value 

### ISSUE THREAD

**Issue by sammdec** [volkov97/react-compound-timer#30]
I have been using this in a project and have noticed when set to run backwards and having a time set for example 3 seconds. When I press start the value just almost immediately to 2 then continues counting down normally. 
I have found a kind of workaround where I set the time to update to just less than 1000. I’m
Using the hook version but not sure if that should make any difference.

**Comment by Ajhaa** [comment]
I encountered the same problem.  I think the problem is, that milliseconds are rounded down to get seconds. For example, 1999ms -> 1s. My workaround is to round the milliseconds with `Math.round`:
`Math.round(timer.getTime() / 1000)`.

**Comment by Julian-quintero** [comment]
Having this exact problem, the others solutions didn't work for me.

**Comment by volkov97** [comment]
now library has **roundUnit** option - it will round till this unit automatically
try version 2.0.3
