### ISSUE TITLE
Display prefix 0 if value smaller than 10

### ISSUE THREAD

**Issue by huy-lv** [volkov97/react-compound-timer#43]
Hello, is there anyway to display Timer.Hour, Timer.Minute,... with prefix 0 if Timer.Hour smaller than 10. For example:
`<Timer.Hours />:<Timer.Minutes />:<Timer.Seconds />`
will render ->
`02:00:23`

**Comment by tirath2** [comment]
you can use formatValue prop
 
`<Timer initialTime={initial}>
            <Timer.Hours
              formatValue={(text) => (text.toString().length > 1 ? text : "0" + text)}
            />
            <Timer.Minutes
              formatValue={(text) => (text.toString().length > 1 ? text : "0" + text)}
            />
            <Timer.Seconds
              formatValue={(text) => (text.toString().length > 1 ? text : "0" + text)}
            />
          </Timer>`
