### ISSUE TITLE
Any plan to support React 17?

### ISSUE THREAD

**Issue by timoleinio** [volkov97/react-compound-timer#61]
Currently React 16 is a peerDependency. Are there any plans to support React 17?

**Comment by yuval-hazaz** [comment]
Does this project still active? are you accepting pull requests?

**Comment by yuval-hazaz** [comment]
For everyone else who gets here - I found this fork with support for React 17
https://www.npmjs.com/package/react-compound-timerv2

**Comment by volkov97** [comment]
try version 2.0.3, should work now, supports react 16,17,18
