### ISSUE TITLE
It does'nt support in react v18.0.2

### ISSUE THREAD

**Issue by Ali-Azizi** [volkov97/react-compound-timer#73]
Hello there,

It seems this component supported in react v 18.0.2 and it caught the below error:

`
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from react-compound-timer@1.2.0
npm ERR! node_modules/react-compound-timer
npm ERR!   react-compound-timer@"*" from the root project
npm ERR!
`

**Comment by volkov97** [comment]
now it supports React 18
