### ISSUE TITLE
Milliseconds component is not working

### ISSUE THREAD

**Issue by revshiv** [volkov97/react-compound-timer#8]
<Timer.Milliseconds />
is not working, always shows 0.

**Comment by volkov97** [comment]
For me it is working, see an example below) @revshiv

https://codesandbox.io/embed/w7x30rvmxk?fontsize=14

**Comment by revshiv** [comment]
I am using direction backward, as default is working fine.

**Comment by volkov97** [comment]
Here is working example with backward count
https://codesandbox.io/embed/8y2n0k187l?fontsize=14
