### ISSUE TITLE
Wrong milliseconds counting with timeToUpdate={1}

### ISSUE THREAD

**Issue by KartaviK** [volkov97/react-compound-timer#9]
Simple example

Correct counting:

```tsx
import * as React from "react";
import Timer from 'react-compound-timer';

class Stopwatch extends React.Component {
    public render() {
        return <Timer timeToUpdate={10}>
            <Timer.Minutes />:<Timer.Seconds />.<Timer.Milliseconds/>
        </Timer>
    }
}

export default Stopwatch;
```

After 10 seconds: `0:10.000`

Wrong counting:

```tsx
import * as React from "react";
import Timer from 'react-compound-timer';

class Stopwatch extends React.Component {
    public render() {
        return <Timer timeToUpdate={1}> // need output all milliseconds
            <Timer.Minutes />:<Timer.Seconds />.<Timer.Milliseconds/>
        </Timer>
    }
}

export default Stopwatch;
```

After 10 seconds: ~`0:2.000`

**Comment by volkov97** [comment]
Great issue
The problem is that timer component can't render it's next state in 1 ms, it needs more
So, this problem will be when timeToUpdate is less then about 16ms

i will think what i can resolve this issue, thank you

**Comment by KartaviK** [comment]
So, at this moment 16ms is minimum value for correct render? Not so good as 1ms, but it also solves my problem :)

**Comment by volkov97** [comment]
Now it count properly, but again - minimum is 16ms. :(
If you will face any problems again - write here again, please!
